services:
  timescaledb:
    container_name: base_timescaledb_container
    image: timescale/timescaledb:latest-pg17
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      TIMESCALEDB_TELEMETRY: off
      POSTGRES_DB: timescaledb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust # disable authentication - not for prod
      PGDATA: /data/postgres