services:
  iot-data-hub-db:
    container_name: base_timescaledb_container
    image: timescale/timescaledb:latest-pg17
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      TIMESCALEDB_TELEMETRY: off
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust # disable authentication - not for prod
      PGDATA: /data/postgres