services:
  iot-data-hub-db:
    extends:
      file: docker-compose.base.yml
      service: iot-data-hub-db
    container_name: iot_data_hub_db_container
    # container_name: timescaledb_container
    # image: timescale/timescaledb:latest-pg17
    # restart: unless-stopped
    # ports:
    #   - 5432:5432
    # environment:
    #   TIMESCALEDB_TELEMETRY: off
    #   POSTGRES_DB: timescaledb
    #   POSTGRES_USER: admin
    #   POSTGRES_PASSWORD: root
    #   POSTGRES_HOST_AUTH_METHOD: trust # disable authentication - not for prod
    #   PGDATA: /data/postgres
    networks:
      - postgres
    volumes:
      - postgres:/data/postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      # PGADMIN_CONFIG_SERVER_MODE: 'False' # disable signing in - not for prod
    ports:
      - "5050:80"
    depends_on:
      - iot-data-hub-db
    networks:
      - postgres
    volumes: 
      - pgadmin:/var/lib/pgadmin

  iot-data-hub:
    container_name: iot_data_hub_container
    restart: unless-stopped
    build: .
    ports:
      - ${IOT_DATA_HUB_PORT:-4000}:3000
    environment:
      DATABASE_URL: postgresql://admin:root@iot-data-hub-db:5432/iotDataHubDb
    depends_on:
      - iot-data-hub-db
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: