name: build-and-test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: check out repository code
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'
      - run: npm ci
      - run: npm run build
      
  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: check out repository code
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'
      - run: npm ci
      - name: Set environment variable
        run: echo "MY_ENV_VAR=myValue" >> $GITHUB_ENV
      - name: Use environment variable
        run: |
          echo "The value of MY_ENV_VAR is $MY_ENV_VAR"
