name: build-test-deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: check out repository code
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'
      - run: npm ci
      - run: npm run build
      
  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: check out repository code
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'
      - run: npm ci
      - name: 'Create .env file'
        run: |
          touch .env
          echo DATABASE_URL=postgresql://admin:root@localhost:5432/timescaledb >> .env
          cat .env
      - run: npm run test:int
      
  deploy:
    needs: test
    uses: Konektix/Cloud/.github/workflows/call-deploy.yml@main
    secrets:
      PAT: ${{ secrets.PAT }}
