name: deploy

on: push

jobs:
  request-restart:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Konektix/Cloud/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"main","inputs":{"service":"${{ github.repository }}"}}'
