name: deploy
on: push

jobs:
  call-request-restart-cloud:
    uses: ./.github/workflows/request-restart-cloud.yml
    secrets:
      PAT: ${{secrets.PAT}}
  # request-restart:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         REPOSITORY=${{github.repository}}
  #         REPOSITORY_NAME=${REPOSITORY#Konektix/}

  #         curl -L \
  #           -X POST \
  #           -H "Accept: application/vnd.github+json" \
  #           -H "Authorization: Bearer ${{secrets.PAT}}" \
  #           -H "X-GitHub-Api-Version: 2022-11-28" \
  #           https://api.github.com/repos/Konektix/Cloud/actions/workflows/deploy.yml/dispatches \
  #           -d '{"ref":"main","inputs":{"service":"'"${REPOSITORY_NAME}"'"}}'
